# Generated by Django 4.2.16 on 2024-10-04 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoosopen', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='interests',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='skills',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.CharField(blank=True, default='Show your personality by adding a fun bio!', max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='github_username',
            field=models.CharField(blank=True, max_length=39, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='graduation_semester',
            field=models.CharField(blank=True, choices=[(1, 'Spring'), (2, 'Fall')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='graduation_year',
            field=models.IntegerField(blank=True, choices=[(2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025), (2026, 2026), (2027, 2027), (2028, 2028), (2029, 2029)], null=True),
        ),
    ]
