# Generated by Django 4.2.16 on 2024-10-04 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hoosopen', '0002_remove_userprofile_interests_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='interests',
            field=models.ManyToManyField(blank=True, to='hoosopen.tag'),
        ),
        migrations.AlterField(
            model_name='userskill',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='hoosopen.userprofile'),
        ),
    ]
