# Generated by Django 4.2.16 on 2024-10-09 15:20

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hoosopen', '0003_userprofile_interests_alter_userskill_user_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_date', models.DateField(default=datetime.date.today)),
                ('message', models.CharField(max_length=500)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hoosopen.project')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hoosopen.userprofile')),
            ],
        ),
    ]
