# Generated by Django 4.2.16 on 2024-10-09 19:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoosopen', '0004_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='post_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
