# Generated by Django 4.2.16 on 2024-10-18 15:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hoosopen', '0007_alter_message_post_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectJoinRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateTimeField(default=datetime.datetime.now)),
                ('comment', models.CharField(blank=True, max_length=500)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hoosopen.project')),
                ('userprofile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hoosopen.userprofile')),
            ],
        ),
    ]
