# Generated by Django 4.2.16 on 2024-10-18 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hoosopen', '0009_projectfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectfile',
            name='userprofile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to='hoosopen.userprofile'),
        ),
    ]
