# Generated by Django 4.2.16 on 2024-10-22 20:13

from django.db import migrations, models
import hoosopen.models


class Migration(migrations.Migration):

    dependencies = [
        ('hoosopen', '0010_projectfile_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectfile',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='projectfile',
            name='tags',
            field=models.ManyToManyField(blank=True, to='hoosopen.tag'),
        ),
        migrations.AddField(
            model_name='projectfile',
            name='title',
            field=models.CharField(blank=True, default='Untitled', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='projectfile',
            name='file',
            field=models.FileField(upload_to=hoosopen.models.upload_to),
        ),
    ]
