# Generated by Django 4.2.16 on 2024-10-24 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoosopen', '0011_projectfile_description_projectfile_tags_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='projectfile',
            name='tags',
            field=models.ManyToManyField(blank=True, to='hoosopen.filetag'),
        ),
    ]