# Generated by Django 4.2.16 on 2024-10-28 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hoosopen', '0012_filetag_alter_projectfile_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectjoinrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('declined', 'Declined'), ('accepted', 'Accepted')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='projectjoinrequest',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_join_requests', to='hoosopen.project'),
        ),
    ]
