# Generated by Django 4.2.16 on 2024-10-28 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoosopen', '0013_projectjoinrequest_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectjoinrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('declined', 'Declined'), ('accepted', 'Accepted')], default='Pending', max_length=10),
        ),
    ]
