# Generated by Django 4.2.16 on 2024-10-28 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoosopen', '0014_alter_projectjoinrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectjoinrequest',
            name='status',
            field=models.CharField(default='Pending', max_length=10),
        ),
    ]
